/*
 *
 * Stats constants
 *
 */

// Fill rate stats
export const FETCH_FILL_RATE_REQUEST = 'app/Stats/FETCH_FILL_RATE_REQUEST';
export const FETCH_FILL_RATE_SUCCESS = 'app/Stats/FETCH_FILL_RATE_SUCCESS';
export const FETCH_FILL_RATE_FAILURE = 'app/Stats/FETCH_FILL_RATE_FAILURE';

// Request distribution stats
export const FETCH_REQUEST_DISTRIBUTION_REQUEST = 'app/Stats/FETCH_REQUEST_DISTRIBUTION_REQUEST';
export const FETCH_REQUEST_DISTRIBUTION_SUCCESS = 'app/Stats/FETCH_REQUEST_DISTRIBUTION_SUCCESS';
export const FETCH_REQUEST_DISTRIBUTION_FAILURE = 'app/Stats/FETCH_REQUEST_DISTRIBUTION_FAILURE';

// Countries distribution stats
export const FETCH_COUNTRIES_DISTRIBUTION_REQUEST = 'app/Stats/FETCH_COUNTRIES_DISTRIBUTION_REQUEST';
export const FETCH_COUNTRIES_DISTRIBUTION_SUCCESS = 'app/Stats/FETCH_COUNTRIES_DISTRIBUTION_SUCCESS';
export const FETCH_COUNTRIES_DISTRIBUTION_FAILURE = 'app/Stats/FETCH_COUNTRIES_DISTRIBUTION_FAILURE';

// Working time distribution stats
export const FETCH_WORKING_TIME_REQUEST = 'app/Stats/FETCH_WORKING_TIME_REQUEST';
export const FETCH_WORKING_TIME_SUCCESS = 'app/Stats/FETCH_WORKING_TIME_SUCCESS';
export const FETCH_WORKING_TIME_FAILURE = 'app/Stats/FETCH_WORKING_TIME_FAILURE';

// Average working time stats
export const FETCH_AVG_WORKING_TIME_REQUEST = 'app/Stats/FETCH_AVG_WORKING_TIME_REQUEST';
export const FETCH_AVG_WORKING_TIME_SUCCESS = 'app/Stats/FETCH_AVG_WORKING_TIME_SUCCESS';
export const FETCH_AVG_WORKING_TIME_FAILURE = 'app/Stats/FETCH_AVG_WORKING_TIME_FAILURE';

// Reference turnaround stats
export const FETCH_REFERENCE_TURNAROUND_REQUEST = 'app/Stats/FETCH_REFERENCE_TURNAROUND_REQUEST';
export const FETCH_REFERENCE_TURNAROUND_SUCCESS = 'app/Stats/FETCH_REFERENCE_TURNAROUND_SUCCESS';
export const FETCH_REFERENCE_TURNAROUND_FAILURE = 'app/Stats/FETCH_REFERENCE_TURNAROUND_FAILURE';

// Reference pubyear distribution stats
export const FETCH_REFERENCE_PUBYEAR_DISTRIBUTION_REQUEST = 'app/Stats/FETCH_REFERENCE_PUBYEAR_DISTRIBUTION_REQUEST'; 
export const FETCH_REFERENCE_PUBYEAR_DISTRIBUTION_SUCCESS = 'app/Stats/FETCH_REFERENCE_PUBYEAR_DISTRIBUTION_SUCCESS'; 
export const FETCH_REFERENCE_PUBYEAR_DISTRIBUTION_FAILURE = 'app/Stats/FETCH_REFERENCE_PUBYEAR_DISTRIBUTION_FAILURE';

// Requests per library stats
export const FETCH_REQUESTS_LIBRARY_REQUEST = 'app/Stats/FETCH_REQUESTS_LIBRARY_REQUEST';
export const FETCH_REQUESTS_LIBRARY_SUCCESS = 'app/Stats/FETCH_REQUESTS_LIBRARY_SUCCESS';
export const FETCH_REQUESTS_LIBRARY_FAILURE = 'app/Stats/FETCH_REQUESTS_LIBRARY_FAILURE';

// OpenAccess References stats
export const FETCH_OPENACCESS_REFERENCES_REQUEST = 'app/Stats/FETCH_OPENACCESS_REFERENCES_REQUEST';
export const FETCH_OPENACCESS_REFERENCES_SUCCESS = 'app/Stats/FETCH_OPENACCESS_REFERENCES_SUCCESS';
export const FETCH_OPENACCESS_REFERENCES_FAILURE = 'app/Stats/FETCH_OPENACCESS_REFERENCES_FAILURE';

// Export CSV
export const EXPORT_CSV_REQUEST = 'app/Stats/EXPORT_CSV_REQUEST';
export const EXPORT_CSV_SUCCESS = 'app/Stats/EXPORT_CSV_SUCCESS';
export const EXPORT_CSV_FAILURE = 'app/Stats/EXPORT_CSV_FAILURE';