FROM --platform=linux/amd64 node:8.15.1
# NOTE: cannot use node's arm/v8 version because packages are not available for such platform too and frontend would not start

WORKDIR /usr/src

RUN apt-get update; apt-get install -y

COPY . /usr/src/app
WORKDIR /usr/src/app

RUN npm install

RUN npm install -g cross-env


#RUN npm run setup


#RUN npm run build:docker
#RUN npm run build

#START
#CMD npm run start:docker
#CMD [ "npm", "start" ]
