/*
 *
 * constants
 *
 */

export const DEFAULT_ACTION = 'app/LandingPage/DEFAULT_ACTION';

export const REQUEST_ACCEPT_PERMISSION = 'app/LandingPage/REQUEST_ACCEPT_PERMISSION';
export const REQUEST_ACCEPT_PERMISSION_SUCCESS = 'app/LandingPage/REQUEST_ACCEPT_PERMISSION_SUCCESS';
export const REQUEST_ACCEPT_PERMISSION_FAIL = 'app/LandingPage/REQUEST_ACCEPT_PERMISSION_FAIL';

export const REQUEST_REJECT_PERMISSION = 'app/LandingPage/REQUEST_REJECT_PERMISSION';
export const REQUEST_REJECT_PERMISSION_SUCCESS = 'app/LandingPage/REQUEST_REJECT_PERMISSION_SUCCESS';
export const REQUEST_REJECT_PERMISSION_FAIL = 'app/LandingPage/REQUEST_REJECT_PERMISSION_FAIL';

export const REQUEST_ERROR = 'app/LandingPage/REQUEST_ERROR';
export const REQUEST_SUCCESS = 'app/LandingPage/REQUEST_SUCCESS';
export const STOP_LOADING = 'app/LandingPage/STOP_LOADING';
