version: '3.4'


services:

  traefik:
    ports:
    - 80:80
    - 443:443
    volumes:
    - "${SSL_CERT_PATH}:/etc/ssl/traefik/localhost.crt"
    - "${SSL_KEY_PATH}:/etc/ssl/traefik/localhost.key"
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./docker/traefik:/etc/traefik

  frontend:
    build: ./frontend
    volumes:
    - ./frontend:/usr/src/app
    - ./.env:/usr/src/.env
    #command: npm start
    command: bash -c "npm install; npm run start:production"
    expose:
    - 3000
    restart: always
    labels:
    - "traefik.port=3000"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:${FRONTEND_DOMAIN};PathPrefix:/,/spidlogin"
    - "traefik.docker.network=proxy"

  frontend_rscvd:
    build: ../RSCVD/frontend
    volumes:
      - ../RSCVD/frontend:/usr/src/app
      - ../RSCVD/.env:/usr/src/.env
    command: bash -c "npm install; npm run start:production"    
    expose:
    - 3000
    restart: always
    labels:
    - "traefik.port=3000"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:devrscvd.bo.cnr.it;PathPrefix:/"
    - "traefik.docker.network=proxy"  

  phpmyadmin:
    labels:
    - "traefik.frontend.auth.basic.users=${PMA_AUTH}"       
#    - "traefik.enable=false"