version: '3.4'

services:
  backend:
    build: ./docker/docker
    env_file:
      - .env
    image: laravel-blog
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/application

  mysql:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=nilde
      - MYSQL_USER=nildeuser
      - MYSQL_PASSWORD=nildepassword
      - MYSQL_ROOT_PASSWORD=nildepassword
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    ports:
      - "81:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db-data:
