version: '3.4'

services:

  nginx:
    image: nginx:alpine
    ports:
    - "${WEBSERVER_EXTERNAL_PORT}:80"
    volumes:
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./:/application
    depends_on:
    - backend

  backend:
    build: ./docker/backend
    image: backend
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/application
#      - /home/halphass/Scaricati:/application/dump
    user: "${UID}"

  mysql:
    image: mysql:5.7
    ports:
    - "${DB_EXTERNAL_PORT}:3306"
    expose:
     - "${DB_EXTERNAL_PORT}"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/data/db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
    - mysql
    environment:
    - MYSQL_USER=${DB_USERNAME}
    - MYSQL_PASSWORD=${DB_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    - PMA_USER=root
    - PMA_PASSWORD=${DB_PASSWORD}
    - PMA_HOST=${DB_HOST}
    ports:
    - "${PMA_PORT}:80"

  horizon:
    build: ./docker/backend
    image: backend
    command: php artisan horizon
    depends_on:
    - mysql
    - redis
    volumes:
    - ./:/application

  redis:
    image: redis:alpine
    ports:
    - "6379:6379"

#volumes:
#  db-data:
