version: '3.4'


services:

  traefik:
    ports:
    - 80:80
    - 443:443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./docker/traefik:/etc/traefik

  frontend:
    build: ./frontend
    volumes:
    - ./frontend:/usr/src/app
    - ./.env:/usr/src/.env
    expose:
    - 3000
    restart: always
    labels:
    - "traefik.port=3000"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:${FRONTEND_DOMAIN}"
    - "traefik.docker.network=proxy"

  phpmyadmin:
    labels:
    - "traefik.frontend.auth.basic.users=${PMA_AUTH}"       
#    - "traefik.enable=false"