version: '3.4'

services:

  traefik:
    image: traefik:v1.7.18
    ports:
      - "${WEBSERVER_EXTERNAL_PORT}:80"
      - 443:443
    volumes:
      - "${SSL_CERT_PATH}:/etc/ssl/traefik/localhost.crt"
      - "${SSL_KEY_PATH}:/etc/ssl/traefik/localhost.key"
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/traefik/local-dev:/etc/traefik
    restart: always
    depends_on:
      - nginx
      - phpmyadmin

  nginx:
    image: nginx:alpine
    #    ports:
    #    - "${WEBSERVER_EXTERNAL_PORT}:80"
    #    - "8001:80"
    expose:
      - 80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application
    depends_on:
      - laravel
    restart: always
    labels:
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.backend=nginx"
      - "traefik.frontend.rule=Host:${API_DOMAIN}"
      - "traefik.docker.network=proxy"

  laravel:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
      args:
        UID: ${UID}
    image: backend
    env_file:
      - .env
    depends_on:
      - mysql
#      - redis
    volumes:
      - ./:/application
    #      - /home/halphass/Scaricati:/application/dump
    user: "${UID}"
    restart: always

  mysql:
    image: mysql:5.7
    #    ports:
    #    - "${DB_EXTERNAL_PORT}:3306"
    expose:
      - "${DB_EXTERNAL_PORT}"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
#      - ./docker/data/db-data:/var/lib/mysql
      - db-data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_HOST=${DB_HOST}
      - PMA_ABSOLUTE_URI=http://${API_DOMAIN}/phpmyadmin/
    #    ports:
    #    - "${PMA_PORT}:80"
    #    - "8002:80"
    expose:
      - 80
    restart: always
    labels:
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.backend=phpmyadmin"
      - "traefik.frontend.rule=Host:${API_DOMAIN};PathPrefixStrip:/phpmyadmin/"
  #    - "traefik.frontend.auth.basic=${PMA_AUTH}"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - ./.env:/usr/src/.env
    command: npm start
    expose:
      - 3000
    restart: always
    labels:
      - "traefik.port=3000"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${FRONTEND_DOMAIN};PathPrefix:/"
      - "traefik.docker.network=proxy"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "10.0.9.0/24"

volumes:
  dbdata:
