version: '3.4'

services:

  traefik:
    image: traefik:v1.7.18
    ports:
    - "${WEBSERVER_EXTERNAL_PORT}:80"
    - 443:443
    volumes:
    - "${SSL_CERT_PATH}:/etc/ssl/traefik/localhost.crt"
    - "${SSL_KEY_PATH}:/etc/ssl/traefik/localhost.key"
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./docker/traefik/local-dev:/etc/traefik
    restart: always
    depends_on:
    - nginx
    - phpmyadmin

  nginx:
    image: nginx:alpine
#    ports:
#    - "${WEBSERVER_EXTERNAL_PORT}:80"
#    - "8001:80"
    expose:
      - 80
    volumes:
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./:/application
    depends_on:
    - laravel
    restart: always
    labels:
    - "traefik.port=80"
    - "traefik.enable=true"
    - "traefik.backend=nginx"
    - "traefik.frontend.rule=Host:${API_DOMAIN}"
    - "traefik.docker.network=proxy"

  laravel:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
      args:
        UID: ${UID}
    image: backend
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/application
#      - /home/halphass/Scaricati:/application/dump
    user: "${UID}"
    restart: always

  mysql:
    image: mysql:5.7
#    ports:
#    - "${DB_EXTERNAL_PORT}:3306"
    expose:
     - "${DB_EXTERNAL_PORT}"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/data/db-data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
    - mysql
    environment:
    - MYSQL_USER=${DB_USERNAME}
    - MYSQL_PASSWORD=${DB_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    - PMA_USER=root
    - PMA_PASSWORD=${DB_PASSWORD}
    - PMA_HOST=${DB_HOST}
    - PMA_ABSOLUTE_URI=http://${API_DOMAIN}/phpmyadmin/
#    ports:
#    - "${PMA_PORT}:80"
#    - "8002:80"
    expose:
    - 80
    restart: always
    labels:
    - "traefik.port=80"
    - "traefik.enable=true"
    - "traefik.backend=phpmyadmin"
    - "traefik.frontend.rule=Host:${API_DOMAIN};PathPrefixStrip:/phpmyadmin/"
#    - "traefik.frontend.auth.basic=${PMA_AUTH}"

  horizon:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
      args:
        UID: ${UID}
    image: backend
    command: php artisan horizon
    depends_on:
    - mysql
    - redis
    volumes:
    - ./:/application
    restart: always

  redis:
    image: redis:alpine
    ports:
    - "6379:6379"
    restart: always

  frontend:
    build: ./frontend_test
    expose:
    - 3000
    restart: always
    labels:
    - "traefik.port=3000"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:${FRONTEND_DOMAIN}"
    - "traefik.docker.network=proxy"

  shibboleth:
#    image: unicon/shibboleth-sp
    build: ./docker/shibboleth
    expose:
      - 80
      - 443
    labels:
    - "traefik.port=443"
    - "traefik.protocol=https"
    - "traefik.enable=true"
    - "traefik.backend=shibboleth"
    - "traefik.frontend.rule=Host:${FRONTEND_DOMAIN};PathPrefix:/Shibboleth.sso/,/sp/,/shibb/"
    - "traefik.docker.network=proxy"
#    - "traefik.frontend.passTLSCert=true"
    - "traefik.proxy.passTLSCert=true"
    volumes:
      - ./docker/shibboleth/etc:/etc/shibboleth
      - ./docker/shibboleth/html:/var/www/html
      - ./docker/shibboleth/shib.conf:/etc/httpd/conf.d/shibb.conf
      - "${SSL_CERT_PATH}:/etc/pki/tls/certs/localhost.crt"
      - "${SSL_KEY_PATH}:/etc/pki/tls/private/localhost.key"
      - ./docker/shibboleth/log/apache-native.log:/var/log/apache2/native.log      
      - ./docker/shibboleth/log/shibd.log:/var/log/shibboleth/shibd.log
      - ./docker/shibboleth/log/shibd_warn.log:/var/log/shibboleth/shibd_warn.log
      - ./docker/shibboleth/log/transaction.log:/var/log/shibboleth/transaction.log
      - ./docker/shibboleth/log/signature.log:/var/log/shibboleth/signature.log
  
  #SPID
  authproxy:
    #image: spid-auth-proxy
    build:
      context: ./docker/spid
      dockerfile: Dockerfile
    expose:
      - 80
      - 443      
    labels:
    - "traefik.port=443"
    - "traefik.protocol=https"
    - "traefik.enable=true"
    - "traefik.backend=authproxy"
    - "traefik.frontend.rule=Host:${FRONTEND_DOMAIN};PathPrefixStrip:/spid/"
    - "traefik.docker.network=proxy"
#    - "traefik.frontend.passTLSCert=true"
    - "traefik.proxy.passTLSCert=true"  
    volumes:
      - '/docker/spid/certs:/opt/shibboleth-sp/certs'
      - '/docker/spid/log:/var/log'
      #- '/docker/spid/certs/saml:/opt/shibboleth-sp/certs:ro'
      #- '${SSL_CERT_PATH}:/etc/pki/tls/certs/server.crt:ro'
      #- '${SSL_KEY_PATH}:/etc/pki/tls/private/server.key:ro'

    environment:
      ORGANIZATION: 'CNR Area della Ricerca di Bologna'
      SERVER_NAME: 'devnilde.bo.cnr.it'
      ENTITY_ID: 'https://devnilde.bo.cnr.it/spid'
      TARGET_BACKEND: 'https://devnilde.bo.cnr.it'
      TARGET_LOCATION: '/spid/login'
      ACS_INDEXES: '1;2'
      ACS_1_LABEL: 'set 1'
      ACS_1_ATTRS: 'name;familyName;fiscalNumber;email'
      ACS_2_LABEL: 'set 2'
      ACS_2_ATTRS: 'spidCode;fiscalNumber'    


#volumes:
#  db-data:

#  networks:
#  - frontend
