version: '3'

services:
  backend:
    build: ./docker/docker
    env_file:
    - .env
    image: laravel-blog
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/application:cached

  horizon:
    build: ./docker/docker
    image: backend
    env_file:
    - .env
    command: php artisan horizon
    depends_on:
      - mysql
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7
    env_file:
    - .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql:cached

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db-data:
