# debug mode
#logLevel = "DEBUG"
#debug = true

# production mode
logLevel = "ERROR"
debug = false
insecureSkipVerify = true

# Traefik will listen for traffic on both HTTP and HTTPS.
defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
# [entryPoints.idpshib]
#    address = ":8088"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/ssl/traefik/localhost.crt"
      keyFile = "/etc/ssl/traefik/localhost.key"
    
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/ssl/traefik/localhost-api.crt"
      keyFile = "/etc/ssl/traefik/localhost-api.key"    

[forwardingTimeouts]
dialTimeout = "60s"

[nginx]
entryPoint = "nginx"

[frontend]
entryPoint = "frontend"


# These options are for Traefik's integration with Docker.
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
#watch = true
exposedByDefault = false

#[file]
#watch = true

# https://docs.traefik.io/configuration/logs/
# Comment out the next line to enable Traefik's access logs.
# [accessLog]




# These options are for Traefik's integration with Let's Encrypt.
# Your certificates are stored inside /acme.json inside the container,
# which is /root/compose/acme.json on your server.
#[acme]
#email = "amministrazione@inkode.it"
#storage = "/etc/traefik/acme/acme.json"
##caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
#caServer = "https://acme-v02.api.letsencrypt.org/directory"
#OnHostRule = false
#entryPoint = "https"
#  [acme.httpChallenge]
#  entryPoint = "http"

#[[acme.domains]]
#  main = "spid-idp.inkode.it"
